"""Generated inventory + severity diff — the audit trail the next
several passes will argue against. Every number lives here in a file
code wrote, not in a prose paragraph in a report.

Two functions produce the committed docs/generated/ artifacts:
  build_inventory       → docs/generated/node_inventory.md
  build_severity_diff   → docs/generated/severity_diff.md

Plus snapshot_severity for capturing the reference state between passes.

Contract, tested by the staleness guards:
  1. Regenerating the inventory in memory produces the same bytes as
     the committed file. A test enforces this so the file cannot drift
     from the code that produces it.
  2. severity_diff regenerates against docs/generated/severity_snapshot.json
     and must show zero deltas until a pass deliberately changes scoring.
"""
from __future__ import annotations

import json
from typing import Optional

from ..graph import SupplyChainGraph
from ..schema import Node
from ..scoring import ScoringConfig


# ------------------------------------------------------------------ #
# Row assembly                                                        #
# ------------------------------------------------------------------ #

def _sv_value(sv) -> Optional[float]:
    if sv is None or sv.value is None:
        return None
    try:
        return float(sv.value)
    except (TypeError, ValueError):
        return None


def _sv_confidence(sv) -> str:
    if sv is None or sv.value is None:
        return "—"
    return sv.confidence.value if hasattr(sv.confidence, "value") else str(sv.confidence)


def _fmt_float(x: Optional[float], places: int = 6) -> str:
    if x is None:
        return "—"
    return f"{x:.{places}f}"


def _concentration_axis(node: Node) -> str:
    """Which axis won the max(inbound, outbound) that produced concentration.
    Returns 'inbound' | 'outbound' | 'tie' | '—' if unscoreable."""
    inb = node.dynamic.inbound_hhi
    out = node.dynamic.outbound_criticality
    if inb is None and out is None:
        return "—"
    if inb is None:
        return "outbound"
    if out is None:
        return "inbound"
    if abs(inb - out) < 1e-9:
        return "tie"
    return "inbound" if inb >= out else "outbound"


# ------------------------------------------------------------------ #
# Inventory                                                           #
# ------------------------------------------------------------------ #

def build_inventory(graph: SupplyChainGraph, config: ScoringConfig) -> str:
    """Return the full docs/generated/node_inventory.md contents as a
    single string. Every value comes from graph state; no rounding for
    display in Section A."""
    scored: list[Node] = []
    unscored: list[Node] = []
    for n in graph.nodes.values():
        if n.dynamic.current_severity is None:
            unscored.append(n)
        else:
            scored.append(n)

    scored.sort(key=lambda n: -(n.dynamic.current_severity or 0.0))
    unscored.sort(key=lambda n: (n.type.value, n.id))

    lines: list[str] = []
    lines.append("# Node inventory — generated")
    lines.append("")
    lines.append("Generated by `backend/app/reporting/inventory.py::build_inventory`.")
    lines.append("Do not edit by hand — regenerated each pass; staleness guarded by "
                 "`backend/tests/test_generated_artifacts.py`.")
    lines.append("")
    lines.append(f"Graph size: {len(graph.nodes)} nodes total "
                 f"({len(scored)} scored, {len(unscored)} unscored).")
    lines.append("")

    # -------- Section A -------- #
    lines.append("## A. Scored nodes (sorted by severity descending)")
    lines.append("")
    headers = [
        "id", "type", "tier", "severity", "concentration",
        "inbound_hhi", "outbound_raw", "outbound_normalized",
        "concentration_axis", "substitutability", "sub_confidence",
        "lead_time_years", "lead_time_confidence",
    ]
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join(["---"] * len(headers)) + "|")

    # Raw outbound needs re-derivation — outbound_criticality on
    # node.dynamic is the normalized post-clamp value. We recompute
    # raw once here so every row can display both.
    from ..scoring.engine import _outbound_criticality_raw
    decay = config.concentration_outbound_decay
    max_hops = config.concentration_outbound_max_hops
    min_influence = config.concentration_outbound_min_influence
    share_field = config.outbound_share_field
    fallback = config.outbound_fallback_to_input_share
    raw_outbound = {
        nid: _outbound_criticality_raw(
            nid, graph, decay, max_hops, min_influence,
            share_field=share_field, fallback=fallback,
        )
        for nid in graph.nodes
    }

    for n in scored:
        tier = n.dynamic.chokepoint_tier.value if n.dynamic.chokepoint_tier else "none"
        row = [
            n.id,
            n.type.value,
            tier,
            _fmt_float(n.dynamic.current_severity, 8),
            _fmt_float(n.dynamic.concentration, 6),
            _fmt_float(n.dynamic.inbound_hhi, 6),
            _fmt_float(raw_outbound.get(n.id), 6),
            _fmt_float(n.dynamic.outbound_criticality, 6),
            _concentration_axis(n),
            _fmt_float(_sv_value(n.static.substitutability), 4),
            _sv_confidence(n.static.substitutability),
            _fmt_float(_sv_value(n.static.lead_time_years), 4),
            _sv_confidence(n.static.lead_time_years),
        ]
        lines.append("| " + " | ".join(row) + " |")

    # -------- Section B -------- #
    lines.append("")
    lines.append("## B. Unscored nodes (missing required static axes)")
    lines.append("")
    lines.append("Grouped by node type. Each row names which axes are missing.")
    lines.append("")

    by_type: dict[str, list[Node]] = {}
    for n in unscored:
        by_type.setdefault(n.type.value, []).append(n)

    for ntype in sorted(by_type):
        rows = by_type[ntype]
        lines.append(f"### {ntype} ({len(rows)})")
        lines.append("")
        lines.append("| id | name | missing_axes |")
        lines.append("|---|---|---|")
        for n in rows:
            missing = n.dynamic.scored_on_default_axes or []
            # H3 fix: a Section B row must NAME at least one missing
            # axis. If the list is empty this node doesn't belong here —
            # it should have scored. Raise rather than write `—`.
            if not missing:
                raise ValueError(
                    f"Node {n.id} is in Section B (unscored) but reports no "
                    f"missing static axes. This should be impossible under "
                    f"the current engine and indicates a bug — investigate "
                    f"before regenerating."
                )
            missing_str = ", ".join(missing)
            lines.append(f"| {n.id} | {n.name} | {missing_str} |")
        lines.append("")

    # -------- Section C -------- #
    lines.append("## C. Tier distribution")
    lines.append("")
    tier_order = ["critical", "high", "moderate", "none", "unscored"]
    counts = {t: 0 for t in tier_order}
    for n in graph.nodes.values():
        tier = n.dynamic.chokepoint_tier.value if n.dynamic.chokepoint_tier else "none"
        counts[tier] = counts.get(tier, 0) + 1
    lines.append("| tier | count |")
    lines.append("|---|---|")
    for t in tier_order:
        lines.append(f"| {t} | {counts[t]} |")
    lines.append(f"| **total** | **{sum(counts.values())}** |")
    lines.append("")

    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ #
# Severity snapshot + diff                                            #
# ------------------------------------------------------------------ #

def snapshot_severity(graph: SupplyChainGraph, captured_at_pass: str) -> dict:
    """Capture the state a future pass will diff against. Returns a dict
    with a `captured_at_pass` label (H4 fix) and a `nodes` map keyed by
    node id. The label names the pass whose END state this snapshot
    represents — so a future diff can say plainly which pass it is
    comparing against, and a first-run diff can say `first-run, no
    prior snapshot` unambiguously."""
    return {
        "captured_at_pass": captured_at_pass,
        "nodes": {
            n.id: {
                "severity": n.dynamic.current_severity,
                "tier": n.dynamic.chokepoint_tier.value if n.dynamic.chokepoint_tier else "none",
                "concentration": n.dynamic.concentration,
                "inbound_hhi": n.dynamic.inbound_hhi,
                "outbound_criticality": n.dynamic.outbound_criticality,
            }
            for n in graph.nodes.values()
        },
    }


def build_severity_diff(snapshot: dict, graph: SupplyChainGraph) -> str:
    """Return the docs/generated/severity_diff.md contents.

    Emits every node with severity_before / severity_after / delta so
    a report claim of "nothing moved" has a file behind it. The diff
    header states plainly whether it is a first-run (empty snapshot)
    or a genuine comparison against a named prior pass (H4 fix).

    Also lists any node in the graph that is missing from the snapshot
    (or vice versa) — those are the kinds of drift that would silently
    make a diff look clean when it wasn't."""
    label = snapshot.get("captured_at_pass") if snapshot else None
    nodes_map = snapshot.get("nodes", {}) if snapshot else {}

    lines: list[str] = []
    lines.append("# Severity diff — generated")
    lines.append("")
    lines.append("Generated by `backend/app/reporting/inventory.py::build_severity_diff`.")
    if not nodes_map:
        lines.append("")
        lines.append("_**First-run comparison:** no prior snapshot is present, so every "
                     "delta below is against an empty reference. Not a valid before/after "
                     "check of a scoring change until the next pass._")
    else:
        lines.append(f"Comparison of prior-pass state `{label or 'unlabelled'}` "
                     f"against the current graph.")
    lines.append("")

    snap_ids = set(nodes_map.keys())
    cur_ids = {n.id for n in graph.nodes.values()}
    only_snap = snap_ids - cur_ids
    only_cur = cur_ids - snap_ids
    if only_snap or only_cur:
        lines.append("## Membership drift")
        lines.append("")
        if only_snap:
            lines.append(f"Nodes in snapshot but not in graph: {sorted(only_snap)}")
        if only_cur:
            lines.append(f"Nodes in graph but not in snapshot: {sorted(only_cur)}")
        lines.append("")

    lines.append("## Per-node severity comparison")
    lines.append("")
    lines.append("| id | severity_before | severity_after | delta | tier_before | tier_after |")
    lines.append("|---|---|---|---|---|---|")

    non_zero_deltas = 0
    tier_changes = 0
    common = sorted(snap_ids & cur_ids)
    for nid in common:
        before = nodes_map[nid]
        node = graph.nodes[nid]
        sev_b = before.get("severity")
        sev_a = node.dynamic.current_severity
        tier_b = before.get("tier", "—")
        tier_a = node.dynamic.chokepoint_tier.value if node.dynamic.chokepoint_tier else "none"

        if sev_b is None and sev_a is None:
            delta_str = "0"
        elif sev_b is None or sev_a is None:
            delta_str = "NULL_TRANSITION"
            non_zero_deltas += 1
        else:
            d = sev_a - sev_b
            delta_str = f"{d:+.10f}"
            if abs(d) > 1e-12:
                non_zero_deltas += 1

        if tier_b != tier_a:
            tier_changes += 1

        lines.append(
            f"| {nid} | {_fmt_float(sev_b, 10)} | {_fmt_float(sev_a, 10)} | "
            f"{delta_str} | {tier_b} | {tier_a} |"
        )

    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Non-zero severity deltas: **{non_zero_deltas}**")
    lines.append(f"- Tier changes: **{tier_changes}**")
    lines.append("")
    if non_zero_deltas == 0 and tier_changes == 0:
        lines.append("_No severity or tier movement — this pass did not touch scoring._")
    elif non_zero_deltas == 0 and tier_changes > 0:
        lines.append(
            "_Zero severity deltas, tiers rebucketed. Expected shape when the "
            "pass touches the tier boundary set but not the severity formula. "
            "The pass report must explain the boundary change and list every "
            "tier reassignment._"
        )
    else:
        lines.append("_Severity moved. The pass author must explain each delta in the pass report._")
    lines.append("")

    return "\n".join(lines) + "\n"
