"""Threshold analysis artifact — Pass B.

Writes docs/generated/threshold_analysis.md, produced by the same
command path as the other generated artifacts. Contains everything
§1.5 of the spec requires so the derivation is reproducible:
  - N scored, N unscored
  - full sorted severity list with adjacent gaps
  - median adjacent gap, separation_factor, separating-gap set
  - derived boundaries + the gap each came from
  - unresolved bands with the node list inside each
  - content hash of the input inventory
  - caveat about weak evidence at N < 30
"""
from __future__ import annotations

import hashlib
from typing import Optional

from ..scoring.thresholds import ThresholdDerivation


def _hash_content(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def build_threshold_analysis(
    derivation: ThresholdDerivation,
    inventory_content: str,
    scored_count: int,
    unscored_count: int,
) -> str:
    """Return the docs/generated/threshold_analysis.md contents."""
    lines: list[str] = []
    lines.append("# Threshold analysis — generated")
    lines.append("")
    lines.append("Generated by `backend/app/reporting/threshold_analysis.py::build_threshold_analysis` "
                 "from the current committed node inventory.")
    lines.append("")
    lines.append(f"- Scored nodes: **{scored_count}**")
    lines.append(f"- Unscored nodes: **{unscored_count}**")
    lines.append(f"- Input inventory SHA-256: `{_hash_content(inventory_content)}`")
    lines.append("")

    if scored_count < 30:
        lines.append(f"> ⚠️ **Weak-evidence caveat.** Gap statistics computed over "
                     f"{scored_count} points are noisy; the derivation should be "
                     f"revisited as static-axis coverage grows and more nodes score. "
                     f"See spec §1.5.")
        lines.append("")

    # -------- Sorted severities with adjacent gaps -------- #
    lines.append("## Sorted severities and adjacent gaps")
    lines.append("")
    lines.append("| rank | id | severity | adjacent gap (from prev) |")
    lines.append("|---:|---|---:|---:|")
    prev_sev: Optional[float] = None
    for i, (nid, sev) in enumerate(derivation.scored, start=1):
        gap = f"{prev_sev - sev:.10f}" if prev_sev is not None else "—"
        lines.append(f"| {i} | {nid} | {sev:.10f} | {gap} |")
        prev_sev = sev
    lines.append("")

    # -------- Statistics + separating set -------- #
    factor = derivation.separation_factor
    med = derivation.median_gap
    thresh = factor * med
    lines.append("## Gap statistics")
    lines.append("")
    lines.append(f"- Median adjacent gap: **{med:.10f}**")
    lines.append(f"- Separation factor: **{factor}**")
    lines.append(f"- Separating threshold (`{factor} × median`): **{thresh:.10f}**")
    lines.append(f"- Separating gaps: **{len(derivation.separating_gaps)}**")
    lines.append("")

    lines.append("### Separating gaps (sorted by midpoint descending)")
    lines.append("")
    lines.append("| upper node | upper sev | lower node | lower sev | size | midpoint |")
    lines.append("|---|---:|---|---:|---:|---:|")
    for g in sorted(derivation.separating_gaps, key=lambda g: -g.midpoint):
        lines.append(
            f"| {g.upper_id} | {g.upper_sev:.10f} | {g.lower_id} | "
            f"{g.lower_sev:.10f} | {g.size:.10f} | {g.midpoint:.10f} |"
        )
    lines.append("")

    # -------- Derived boundaries -------- #
    lines.append("## Derived boundaries")
    lines.append("")
    lines.append("| boundary | value | gap it came from |")
    lines.append("|---|---:|---|")
    for name in ("critical", "high", "moderate"):
        v = derivation.boundaries.get(name, 0.0)
        g = derivation.boundary_gap.get(name)
        src = (
            f"{g.upper_id} → {g.lower_id} (size {g.size:.10f})"
            if g is not None
            else "**no separating gap** — see unresolved bands"
        )
        lines.append(f"| {name}/{'high' if name == 'critical' else 'moderate' if name == 'high' else 'none'} | {v:.10f} | {src} |")
    lines.append("")

    # -------- Unresolved bands -------- #
    lines.append("## Unresolved bands")
    lines.append("")
    if not derivation.unresolved_bands:
        lines.append("_None — every required boundary landed on a separating gap._")
    else:
        for band in derivation.unresolved_bands:
            nodes_in_band = [
                nid for nid, sev in derivation.scored
                if band.lower <= sev <= band.upper
            ]
            lines.append(f"### {' / '.join(band.tiers)}")
            lines.append("")
            lines.append(f"- Span: [{band.lower:.10f}, {band.upper:.10f}]")
            lines.append(f"- Reason: {band.reason}")
            lines.append(f"- Nodes inside ({len(nodes_in_band)}):")
            for nid in nodes_in_band:
                lines.append(f"  - {nid}")
            lines.append("")
    lines.append("")

    return "\n".join(lines) + "\n"
